name: Code linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip --disable-pip-version-check install pipenv
        pipenv install --dev

    - name: Analysing the formatting with black
      run: |
          pipenv run black $(git ls-files '*.py') --check --diff --color

    - name: Analysing the code with pylint
      run: |
        pipenv run pylint $(git ls-files '*.py') --output-format=colorized

    - name: Analysing the code with flake8
      run: |
        pipenv run flake8 $(git ls-files '*.py')
